### Working with Tensors

In [1]:
# imports
import torch
import math
from pprint import pprint

#### 1. creating tensors with factory functions

In [2]:
# Create an empty tensor
n_rows, n_cols = 3, 4
empty_tensor = torch.empty(n_rows, n_cols)
empty_tensor

tensor([[ 9.1437e-35, -1.8693e+29,  3.2264e+01, -1.9705e-10],
        [-7.0247e+31,  3.2264e+01,  3.2092e-39,  1.2469e-36],
        [ 1.0989e-22, -1.9438e+29,  2.9310e-14,  1.2871e-05]])

In [3]:
### Tensor initialization on creation
zeros_tensor = torch.zeros(n_rows, n_cols)
zeros_tensor


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
ones_tensor = torch.ones(n_rows, n_cols)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
## set the seed so this values will be regenerated again
torch.manual_seed(42)
randoms_tensor = torch.rand(n_rows, n_cols)
randoms_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [6]:
# creating tensors with same dimensions( as an exisiting tensors
empty_like_empty_tensor = torch.empty_like(empty_tensor)
rand_like_random_tensor = torch.rand_like(randoms_tensor)
empty_like_empty_tensor

tensor([[-1.4855e+15,  3.2701e-41,  0.0000e+00,  0.0000e+00],
        [        nan,  6.0090e-01,  1.7753e+28,  4.4339e+27],
        [ 1.7975e+19,  6.9481e+22,  5.5757e-02,  1.8728e+31]])

In [7]:
zeros_like_zeros_tensor = torch.zeros_like(zeros_tensor)
zeros_like_zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
 rand_like_random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [9]:
assert rand_like_random_tensor.shape == randoms_tensor.shape," not equals shape"

In [10]:
### creating tensors with data instatiation
some_constants = torch.tensor([[3.14, 2.7],[1.6, 0.0027]]) # using list of list
some_constants, some_constants.shape, some_constants.dtype


(tensor([[3.1400e+00, 2.7000e+00],
         [1.6000e+00, 2.7000e-03]]),
 torch.Size([2, 2]),
 torch.float32)

In [11]:
some_ints = torch.tensor((1,2,3,35)) # using tuples
some_ints, some_ints.shape, some_ints.dtype

(tensor([ 1,  2,  3, 35]), torch.Size([4]), torch.int64)

In [12]:
more_ints = torch.tensor(([1,2.3,3], (4,5,6), [i*3 for i in range(0,3)] ), dtype=torch.int8) # using different collections types and assigning data types
more_ints, more_ints.shape, more_ints.dtype

(tensor([[1, 2, 3],
         [4, 5, 6],
         [0, 3, 6]], dtype=torch.int8),
 torch.Size([3, 3]),
 torch.int8)

In [13]:
# convert to the datatype to another type,
more_ints.to(torch.float64)# its seems you can't type cast upwards
more_ints

tensor([[1, 2, 3],
        [4, 5, 6],
        [0, 3, 6]], dtype=torch.int8)

In [14]:
more_ints.to(torch.int32)
more_ints

tensor([[1, 2, 3],
        [4, 5, 6],
        [0, 3, 6]], dtype=torch.int8)

In [15]:
torch.multiply(more_ints ,3.213)

tensor([[ 3.2130,  6.4260,  9.6390],
        [12.8520, 16.0650, 19.2780],
        [ 0.0000,  9.6390, 19.2780]])

In [16]:
more_ints 

tensor([[1, 2, 3],
        [4, 5, 6],
        [0, 3, 6]], dtype=torch.int8)

In [17]:
more_ints = torch.mul(more_ints , 3.14)

In [18]:
more_ints, more_ints.dtype

(tensor([[ 3.1400,  6.2800,  9.4200],
         [12.5600, 15.7000, 18.8400],
         [ 0.0000,  9.4200, 18.8400]]),
 torch.float32)

In [19]:
some_ints, some_ints.dtype

(tensor([ 1,  2,  3, 35]), torch.int64)

In [20]:
some_ints = some_ints * 3.12
some_ints, some_ints.dtype

(tensor([  3.1200,   6.2400,   9.3600, 109.2000]), torch.float32)